services:
  n8n_postgres:
    image: postgres:16
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_NON_ROOT_USER
      - POSTGRES_NON_ROOT_PASSWORD
    volumes:
      - ./src/n8n_db_storage:/var/lib/postgresql/data
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    networks:
      - n8n_network

  n8n:
    image: docker.n8n.io/n8nio/n8n:1.100.0
    restart: always
    ports:
      - 5678:5678
    environment:
      # Postgres
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=n8n_postgres # service name
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${POSTGRES_DB}
      - DB_POSTGRESDB_USER=${POSTGRES_NON_ROOT_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_NON_ROOT_PASSWORD}
    volumes:
      - ./src/n8n_storage:/home/node/.n8n
    networks:
      - n8n_network

  mysql-db-service:
    image: mysql:9.3.0
    container_name: mysql_db_container
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    ports:
      - "3306:3306"
    volumes:
      - ./src/mysql_db_data:/var/lib/mysql
    restart: always
    networks:
      - n8n_network

networks:
  n8n_network: